name: NPM Package

on: push
#  release:
#    types: [created]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 17
       - run: npm ci
       - run: apt update
       - run: apt build-dep --yes --no-install-recommends poppler
       - run: apt install --yes --no-install-recommends ninja-build libcurl4-openssl-dev git ca-certificates locales libgtk-3-dev libbrotli-dev libboost-container-dev qt6-base-dev
       - run: node build.js
       - uses: actions/upload-artifact@v3
         with:
           name: ubuntu-build
           path: poppler/build/
  build-windows:
    runs-on: windows-latest
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 17
       - uses: microsoft/setup-msbuild@v1.1
       - run: npm ci
       - run: node build.js
       - uses: actions/upload-artifact@v3
         with:
           name: windows-build
           path: poppler/build/
