name: NPM Package

on: push
#  release:
#    types: [created]

jobs:
#  build-ubuntu:
#    runs-on: ubuntu-latest
#    steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 17
#       - run: npm ci
#       - run: sudo sh -c "echo 'deb-src http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse' >> /etc/apt/sources.list"
#       - run: sudo apt update
#       - run: sudo apt build-dep --yes --no-install-recommends poppler
#       - run: sudo apt install --yes --no-install-recommends ninja-build libcurl4-openssl-dev git ca-certificates locales libgtk-3-dev libbrotli-dev libboost-container-dev qt6-base-dev
#       - run: node build.js
#       - uses: actions/upload-artifact@v3
#         with:
#           name: ubuntu-build
#           path: poppler/build/
  build-windows:
    runs-on: ubuntu-latest
    container: dockcross/windows-static-x64
    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 17
       #- uses: microsoft/setup-msbuild@v1.1
       - uses: ashutoshvarma/setup-ninja@v1.1
       #- uses: msys2/setup-msys2@v2
       #  with:
       #    install: >-
       #      mingw-w64-cairo
       - run: npm ci
       - run: node build.js
       - uses: actions/upload-artifact@v3
         with:
           name: windows-build
           path: poppler/build/
